#index:
#    path: /
#    controller: App\Controller\DefaultController::index

easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/EasyAdminController.php"
  type:     annotation
  prefix:   /admin
